sudo: required
services:
  - docker

before_install:
  - docker build -t larsmaechel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true larsmaechel/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-077010648160"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"